### ISSUE TITLE
Inconsistency in lab

### ISSUE THREAD

**Issue by kronosapiens** [learn-co-curriculum/angular-multiple-controllers-lab#2]
There are some inconsistencies in this lab:

The README asks the student to write both Contact and Staff controllers inside a single file. Yet, the repo skeleton includes a separate empty file for each controller.

The README instructs the student to create a button on index.html which calls some JS code. Yet, the tests do not test for this button and I was able to pass all tests without creating one.

**Comment by aturkewi** [comment]
@kronosapiens I resolved the first part of this issue in PR #3 

As for the second part (not testing the button), that's not yet covered in this part of the curriculum. Testing directives comes up next. Also, at the moment, the learn gem can not run multiple test suites. It's currently using Karma and Jasmine, but to test the button we'd need to use Protractor.
